### ISSUE TITLE
Mobile to Web View Transform

### ISSUE THREAD

**Issue by bgoktugozdemir** [flutterturkey/festival_flutterturkiye_org#113]
While the website working on a web browser and its view is the mobile version. If the user makes it larger when the app bar is open, it throws a Null exception.

**Comment by adem-emre** [comment]
Mobile to WebView is fixed #117

**Comment by adem-emre** [comment]
#117

**Comment by adem-emre** [comment]
Mobile to WebView is fixed #117

**Comment by adem-emre** [comment]
![mobile_to_web_view](https://user-images.githubusercontent.com/79714460/158019021-00d708f6-dcee-460e-b106-caaad6a419d8.gif)
