### ISSUE TITLE
Flutter 2.0

### ISSUE THREAD

**Issue by bgoktugozdemir** [flutterturkey/festival_flutterturkiye_org#56]
- [x] Flutter 2.0 Upgrading 
- [x] Workflow Update

**Comment by MuTe33** [comment]
Hey guys, 

I was checking out your repository and I assume you forgot to update your README file in section `Current Flutter Development Version`. You are stating that you were using version `1.26.0-8.0.pre` with Dart SDK version `2.12.0-179.0.dev` which for me did not work. I got a pubspec error indicating that for example `url_launcher` requires at least Dart SDK version `2.12.0-259.9.beta`. Therefore I upgraded my SDK version and now working. Now I've seen this issue with the Flutter 2.0 upgrading checkmarked assuming you already bump up the version? :) 

I would have created a small PR but was not sure with what kind of flutter version you are currently working. 

Another thing, is this repository open for contributions from community? I really would like to make some 😁 

All the best,
Murat
