### ISSUE TITLE
Variable Naming in SponsorRepository

### ISSUE THREAD

**Issue by MuTe33** [flutterturkey/festival_flutterturkiye_org#78]
Hey, 

even though this is a really small issue and fix, I wanted to stick to the rules and open an issue for this. 

In `SponsorRepository` the getter `speakers` is named `_sponsors`. And down in the method the same.  I assume this is by mistake. I opened a small PR to fix the wording as this might be confusing. I was just stumbling across while reading the code.

Best,
Murat

**Comment by bgoktugozdemir** [comment]
Thank you for your interest and attention.
